-- Data Analyst Task 8: Window Functions
-- Generated by Python Automation Script

-- Query: Ranked Customers
SELECT 
                region,
                customer_name,
                SUM(sales) as total_sales,
                ROW_NUMBER() OVER (PARTITION BY region ORDER BY SUM(sales) DESC) as row_num,
                RANK() OVER (PARTITION BY region ORDER BY SUM(sales) DESC) as rank_val,
                DENSE_RANK() OVER (PARTITION BY region ORDER BY SUM(sales) DESC) as dense_rank_val
            FROM superstore
            GROUP BY region, customer_name
            ORDER BY region, total_sales DESC;;

-- Query: Running Total
SELECT 
                order_date,
                SUM(sales) as daily_sales,
                SUM(SUM(sales)) OVER (ORDER BY order_date) as running_total_sales
            FROM superstore
            GROUP BY order_date
            ORDER BY order_date;;

-- Query: Mom Growth
WITH monthly_sales AS (
                SELECT 
                    strftime('%Y-%m', order_date) as sale_month,
                    SUM(sales) as current_month_sales
                FROM superstore
                GROUP BY sale_month
            )
            SELECT 
                sale_month,
                current_month_sales,
                LAG(current_month_sales) OVER (ORDER BY sale_month) as previous_month_sales,
                (current_month_sales - LAG(current_month_sales) OVER (ORDER BY sale_month)) as growth_amount
            FROM monthly_sales;;

-- Query: Top 3 Products
WITH product_ranks AS (
                SELECT 
                    category,
                    product_name,
                    SUM(sales) as total_sales,
                    DENSE_RANK() OVER (PARTITION BY category ORDER BY SUM(sales) DESC) as rank_val
                FROM superstore
                GROUP BY category, product_name
            )
            SELECT * FROM product_ranks
            WHERE rank_val <= 3;;

